/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'tiktokColor' : string,
  'alternatePhone' : string,
  'youTubeColor' : string,
  'email' : string,
  'tiktokIcon' : string,
  'youTubeUrl' : string,
  'address' : string,
  'facebookColor' : string,
  'facebookIcon' : string,
  'primaryPhone' : string,
  'facebookUrl' : string,
  'footerText' : string,
  'tiktokUrl' : string,
  'youTubeIcon' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Course {
  'id' : bigint,
  'descriptionBn' : string,
  'descriptionEn' : string,
  'titleBn' : string,
  'titleEn' : string,
}
export type CourseDuration = { 'thirtyDays' : null } |
  { 'sixtyDays' : null };
export type CourseType = { 'car' : null } |
  { 'motorcycle' : null };
export interface DriverDocument {
  'id' : bigint,
  'blob' : ExternalBlob,
  'name' : string,
  'description' : string,
}
export interface DrivingSchoolProfile {
  'owner' : string,
  'name' : string,
  'alternatePhone' : string,
  'registrationNumber' : string,
  'email' : string,
  'website' : string,
  'addressBn' : string,
  'addressEn' : string,
  'registrationTextBn' : string,
  'registrationTextEn' : string,
  'phone' : string,
  'taglineBn' : string,
  'taglineEn' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : bigint,
  'blob' : ExternalBlob,
  'name' : string,
  'description' : string,
}
export interface RegistrationInquiry {
  'name' : string,
  'message' : string,
  'address' : string,
  'timestamp' : Time,
  'phone' : string,
  'course' : string,
}
export interface Service {
  'id' : bigint,
  'nameBn' : string,
  'nameEn' : string,
  'descriptionBn' : string,
  'descriptionEn' : string,
}
export interface SocialMediaLink {
  'url' : string,
  'icon' : string,
  'name' : string,
  'platform' : string,
  'isActive' : boolean,
}
export interface StudentRecord {
  'id' : bigint,
  'studentName' : string,
  'admissionDate' : string,
  'createdAt' : Time,
  'reference' : string,
  'fathersName' : string,
  'totalFee' : bigint,
  'courseDuration' : CourseDuration,
  'updatedAt' : Time,
  'address' : string,
  'phoneNumber' : string,
  'paidAmount' : bigint,
  'courseType' : CourseType,
  'remarks' : string,
  'dueAmount' : bigint,
}
export interface TeamMember {
  'id' : bigint,
  'name' : string,
  'positionBn' : string,
  'positionEn' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebsiteContent {
  'aboutUsBn' : string,
  'aboutUsEn' : string,
  'taglineBn' : string,
  'taglineEn' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDocument' : ActorMethod<[ExternalBlob, string, string], undefined>,
  'addGalleryImage' : ActorMethod<[ExternalBlob, string, string], undefined>,
  'addStudentRecord' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      CourseType,
      CourseDuration,
      bigint,
      bigint,
      string,
      string,
      string,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanupOldEntries' : ActorMethod<[bigint], undefined>,
  'clearFormEntries' : ActorMethod<[], undefined>,
  'deleteStudentRecord' : ActorMethod<[bigint], undefined>,
  'getAllContactSubmissionsSorted' : ActorMethod<
    [bigint],
    Array<ContactSubmission>
  >,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllRegistrationInquiriesSorted' : ActorMethod<
    [bigint],
    Array<RegistrationInquiry>
  >,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllStudentRecords' : ActorMethod<[], Array<StudentRecord>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getCourseById' : ActorMethod<[bigint], Course>,
  'getDocuments' : ActorMethod<[], Array<DriverDocument>>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getSchoolProfile' : ActorMethod<[], DrivingSchoolProfile>,
  'getSocialMediaLinks' : ActorMethod<[], Array<SocialMediaLink>>,
  'getStudentRecordsSorted' : ActorMethod<[bigint], Array<StudentRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebsiteContent' : ActorMethod<[], WebsiteContent>,
  'initializeData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSocialMediaLinks' : ActorMethod<[], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitRegistrationInquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateCourse' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateService' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateSocialMediaLink' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    undefined
  >,
  'updateStudentRecord' : ActorMethod<[bigint, StudentRecord], undefined>,
  'updateTeamMember' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];