/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CourseType = IDL.Variant({
  'car' : IDL.Null,
  'motorcycle' : IDL.Null,
});
export const CourseDuration = IDL.Variant({
  'thirtyDays' : IDL.Null,
  'sixtyDays' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'descriptionBn' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'titleBn' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const RegistrationInquiry = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'nameBn' : IDL.Text,
  'nameEn' : IDL.Text,
  'descriptionBn' : IDL.Text,
  'descriptionEn' : IDL.Text,
});
export const StudentRecord = IDL.Record({
  'id' : IDL.Nat,
  'studentName' : IDL.Text,
  'admissionDate' : IDL.Text,
  'createdAt' : Time,
  'reference' : IDL.Text,
  'fathersName' : IDL.Text,
  'totalFee' : IDL.Nat,
  'courseDuration' : CourseDuration,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'paidAmount' : IDL.Nat,
  'courseType' : CourseType,
  'remarks' : IDL.Text,
  'dueAmount' : IDL.Nat,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'positionBn' : IDL.Text,
  'positionEn' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'tiktokColor' : IDL.Text,
  'alternatePhone' : IDL.Text,
  'youTubeColor' : IDL.Text,
  'email' : IDL.Text,
  'tiktokIcon' : IDL.Text,
  'youTubeUrl' : IDL.Text,
  'address' : IDL.Text,
  'facebookColor' : IDL.Text,
  'facebookIcon' : IDL.Text,
  'primaryPhone' : IDL.Text,
  'facebookUrl' : IDL.Text,
  'footerText' : IDL.Text,
  'tiktokUrl' : IDL.Text,
  'youTubeIcon' : IDL.Text,
});
export const DriverDocument = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const DrivingSchoolProfile = IDL.Record({
  'owner' : IDL.Text,
  'name' : IDL.Text,
  'alternatePhone' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'addressBn' : IDL.Text,
  'addressEn' : IDL.Text,
  'registrationTextBn' : IDL.Text,
  'registrationTextEn' : IDL.Text,
  'phone' : IDL.Text,
  'taglineBn' : IDL.Text,
  'taglineEn' : IDL.Text,
});
export const SocialMediaLink = IDL.Record({
  'url' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'platform' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const WebsiteContent = IDL.Record({
  'aboutUsBn' : IDL.Text,
  'aboutUsEn' : IDL.Text,
  'taglineBn' : IDL.Text,
  'taglineEn' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDocument' : IDL.Func([ExternalBlob, IDL.Text, IDL.Text], [], []),
  'addGalleryImage' : IDL.Func([ExternalBlob, IDL.Text, IDL.Text], [], []),
  'addStudentRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        CourseType,
        CourseDuration,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanupOldEntries' : IDL.Func([IDL.Nat], [], []),
  'clearFormEntries' : IDL.Func([], [], []),
  'deleteStudentRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllContactSubmissionsSorted' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllRegistrationInquiriesSorted' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RegistrationInquiry)],
      ['query'],
    ),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllStudentRecords' : IDL.Func([], [IDL.Vec(StudentRecord)], ['query']),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getCourseById' : IDL.Func([IDL.Nat], [Course], ['query']),
  'getDocuments' : IDL.Func([], [IDL.Vec(DriverDocument)], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getSchoolProfile' : IDL.Func([], [DrivingSchoolProfile], ['query']),
  'getSocialMediaLinks' : IDL.Func([], [IDL.Vec(SocialMediaLink)], ['query']),
  'getStudentRecordsSorted' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StudentRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
  'initializeData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSocialMediaLinks' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitRegistrationInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCourse' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSocialMediaLink' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateStudentRecord' : IDL.Func([IDL.Nat, StudentRecord], [], []),
  'updateTeamMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CourseType = IDL.Variant({ 'car' : IDL.Null, 'motorcycle' : IDL.Null });
  const CourseDuration = IDL.Variant({
    'thirtyDays' : IDL.Null,
    'sixtyDays' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'descriptionBn' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'titleBn' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const RegistrationInquiry = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'nameBn' : IDL.Text,
    'nameEn' : IDL.Text,
    'descriptionBn' : IDL.Text,
    'descriptionEn' : IDL.Text,
  });
  const StudentRecord = IDL.Record({
    'id' : IDL.Nat,
    'studentName' : IDL.Text,
    'admissionDate' : IDL.Text,
    'createdAt' : Time,
    'reference' : IDL.Text,
    'fathersName' : IDL.Text,
    'totalFee' : IDL.Nat,
    'courseDuration' : CourseDuration,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'paidAmount' : IDL.Nat,
    'courseType' : CourseType,
    'remarks' : IDL.Text,
    'dueAmount' : IDL.Nat,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'positionBn' : IDL.Text,
    'positionEn' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'tiktokColor' : IDL.Text,
    'alternatePhone' : IDL.Text,
    'youTubeColor' : IDL.Text,
    'email' : IDL.Text,
    'tiktokIcon' : IDL.Text,
    'youTubeUrl' : IDL.Text,
    'address' : IDL.Text,
    'facebookColor' : IDL.Text,
    'facebookIcon' : IDL.Text,
    'primaryPhone' : IDL.Text,
    'facebookUrl' : IDL.Text,
    'footerText' : IDL.Text,
    'tiktokUrl' : IDL.Text,
    'youTubeIcon' : IDL.Text,
  });
  const DriverDocument = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const DrivingSchoolProfile = IDL.Record({
    'owner' : IDL.Text,
    'name' : IDL.Text,
    'alternatePhone' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'addressBn' : IDL.Text,
    'addressEn' : IDL.Text,
    'registrationTextBn' : IDL.Text,
    'registrationTextEn' : IDL.Text,
    'phone' : IDL.Text,
    'taglineBn' : IDL.Text,
    'taglineEn' : IDL.Text,
  });
  const SocialMediaLink = IDL.Record({
    'url' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'platform' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const WebsiteContent = IDL.Record({
    'aboutUsBn' : IDL.Text,
    'aboutUsEn' : IDL.Text,
    'taglineBn' : IDL.Text,
    'taglineEn' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDocument' : IDL.Func([ExternalBlob, IDL.Text, IDL.Text], [], []),
    'addGalleryImage' : IDL.Func([ExternalBlob, IDL.Text, IDL.Text], [], []),
    'addStudentRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          CourseType,
          CourseDuration,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanupOldEntries' : IDL.Func([IDL.Nat], [], []),
    'clearFormEntries' : IDL.Func([], [], []),
    'deleteStudentRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllContactSubmissionsSorted' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllRegistrationInquiriesSorted' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RegistrationInquiry)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllStudentRecords' : IDL.Func([], [IDL.Vec(StudentRecord)], ['query']),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getCourseById' : IDL.Func([IDL.Nat], [Course], ['query']),
    'getDocuments' : IDL.Func([], [IDL.Vec(DriverDocument)], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getSchoolProfile' : IDL.Func([], [DrivingSchoolProfile], ['query']),
    'getSocialMediaLinks' : IDL.Func([], [IDL.Vec(SocialMediaLink)], ['query']),
    'getStudentRecordsSorted' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StudentRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
    'initializeData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSocialMediaLinks' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitRegistrationInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCourse' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSocialMediaLink' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateStudentRecord' : IDL.Func([IDL.Nat, StudentRecord], [], []),
    'updateTeamMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };